# Generated by Django 4.2.6 on 2023-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='1.jpg', upload_to='user_photo/'),
        ),
    ]
